
;               SEGMENT REGISTER:OFFSET
;STACK SEGMENT  SS:SP/BP
;DATA SEGMENT   DS:DI/SI
;EXTRA SEGMENT  ES:DI/SI
;CODE SEGMENT   CS:IP

;LOGICAL ADDRESS SEGMENT REGISTRES ADDRESS : OFFSET ADDRESS
; PHYSICAL ADDRESS = SEGMENT REGISTER ADDRESS*10 + OFFSET 



MOV AX,1234H 
MOV BX,0ABCDH ;WHY 0 AT FRONT? BECAUSE 8086 MEMORY ALLOWS ONLY VALUES FROM 0-9

    MOV [0024H],AX
    MOV CX,AX
    PUSH AX
    POP DX
    PUSH BX
    
